-- ============================================================================
-- people_outlay.sql — People Outlay Map for the Strategic Workforce Plan
-- ============================================================================
-- Idempotent. Paste into the Supabase SQL editor.
--
-- The "wow upgrade" decided in the 2026-06-02 pricing session that
-- differentiates Shapi from any consultant: for each role gap identified in
-- the workforce_plan, surface 3-5 verified candidates from the pool with
-- match score + time-to-hire estimate + click-through to their profile.
-- Consultants hand a deck and leave; Shapi hands a deck WITH the actual
-- humans to execute it. No competitor has a verified candidate pool.
--
-- New column on tier_b_engagements:
--   people_outlay  jsonb  — generated by the map_people_outlay action,
--                          contains role_gaps[] with verified_candidates[]
--                          + a summary block. Shape documented in
--                          /api/company/tier-b/route.ts.
-- ============================================================================

alter table public.tier_b_engagements
  add column if not exists people_outlay jsonb;
